name: KPersonal-android
on: [push, pull_request]

jobs: 
  windows:
    name: Android
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.3'
          channel: 'stable'

      - name: Flutter Version
        run: flutter --version