name: KPersonal-macos
on: [push, pull_request]

jobs: 
  windows:
    name: MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.3'
          channel: 'stable'

      - name: Flutter Version
        run: flutter --version
